Lil

diff --git a/pakt-dry b/pakt-dry
--- a/pakt-dry
+++ b/pakt-dry
@@ -43,7 +43,7 @@ for arg in "$@"; do
 	case "$arg" in
 		-*)
 			if [ -n "$FLAG" ]; then
-				"PAKT: ERROR: pakt only takes one flag. Exiting ..."
+				echo "PAKT: ERROR: pakt only takes one flag. Exiting ..."
 				exit 1
 			fi
 			FLAG="$arg"
@@ -53,22 +53,30 @@ for arg in "$@"; do
 	esac
 done
 
-if [ "$FLAG" = "" ]; then
-	for arg in $(echo "$REST" | tr ' ' '\n'); do
-		echo -e "$arg\n--------------------"
-		case "$arg" in
-			"+"*)
-				cat "$DATA_PATH/${arg#+}"
-				;;
-			*)
-				cat "$arg"
-				;;
-		esac
-		echo
-	done
+case "$FLAG" in
+	"-a"|"--add"|"-r"|"--remove")
+		;;
+	"")
+		for arg in $(echo "$REST" | tr ' ' '\n'); do
+			echo -e "$arg\n--------------------"
+			case "$arg" in
+				"+"*)
+					cat "$DATA_PATH/${arg#+}"
+					;;
+				*)
+					cat "$arg"
+					;;
+			esac
+			echo
+		done
 
-	exit
-fi
+		exit
+		;;
+	*)
+		echo "PAKT-DRY: ERROR: invalid flag '$FLAG'"
+		exit 1
+		;;
+esac
 
 # From this point on, pakt-dry applies the same logic as in pakt to (de-)categorize the packages.
 
@@ -131,7 +139,7 @@ for tmpfile in /tmp/pakt-dry/*; do
 	touch $catfile
 
 	for pkg in $(cat "$tmpfile"); do
-		if [ "$FLAG" = "-r" ]; then
+		if [ "$FLAG" = "-r" ] || [ "$FLAG" = "--remove" ]; then
 			# Remove package from category file.
 			# You can't pipe directly into tmpfile because it would encounter an empty file.
 			sed -i "/^$pkg$/d" "$catfile"
